=== Opentrons/opentrons/shared-data/pipette/schemas/2/pipetteLiquidPropertiesSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "positiveNumber": {
      "type": "number",
      "minimum": 0
    },
    "xyzArray": {
      "type": "array",
      "description": "Array of 3 numbers, [x, y, z]",
      "items": { "type": "number" },
      "minItems": 3,
      "maxItems": 3
    },
    "liquidHandlingSpecs": {
      "description": "Object containing linear equations for translating between uL of liquid and mm of plunger travel. There is one linear equation for aspiration and one for dispense",
      "type": "object",
      "required": ["aspirate", "dispense"],
      "additionalProperties": false,
      "properties": {
        "aspirate": { "$ref": "#/definitions/xyzArray" },
        "dispense": { "$ref": "#/definitions/xyzArray" }
      }
    },
    "flowRate": {
      "description": "Object with a default value and optional dict keyed by api level. If API level is unavailable, default is used.",
      "type": "object",
      "required": ["default", "valuesByApiLevel"],
      "properties": {
        "default": {
          "$ref": "#/definitions/positiveNumber",
          "$comment": "The default value of the flowrate"
        },
        "valuesByApiLevel": { "type": "object", "required": [] }
      }
    }
  },
  "type": "object",
  "required": [
    "$otSharedSchema",
    "maxVolume",
    "minVolume",
    "defaultTipracks",
    "supportedTips"
  ],
  "additionalProperties": false,
  "properties": {
    "$otSharedSchema": {
      "type": "string",
      "description": "The path to a valid Opentrons shared schema relative to the shared-data directory, without its extension. For instance, #/pipette/schemas/2/pipetteLiquidPropertiesSchema.json is a reference to this schema."
    },
    "supportedTips": {
      "type": "object",
      "description": "A container of supported tip types",
      "properties": {
        "patternProperties": {
          "description": "Tip specific liquid handling properties for a given pipette. Using the active tip on a pipette, we will look up the pipetting configurations associated with that tip+pipette combo.",
          "type": "object",
          "$comment": "Example key: 't50'",
          "^t[0-9]{2,4}": {
            "required": [
              "defaultAspirateFlowRate",
              "defaultDispenseFlowRate",
              "defaultBlowOutFlowRate",
              "aspirate",
              "dispense"
            ],
            "properties": {
              "defaultAspirateFlowRate": {
                "$ref": "#/definitions/flowRate",
                "$comment": "for lowVolumeDefault only, the flowRate matches the uiMaxFlowRate. This does not change physical behavior and was made for UI purposes"
              },
              "defaultDispenseFlowRate": {
                "$ref": "#/definitions/flowRate",
                "$comment": "for lowVolumeDefault only, the flowRate matches the uiMaxFlowRate. This does not change physical behavior and was made for UI purposes"
              },
              "defaultBlowOutFlowRate": {
                "$ref": "#/definitions/flowRate",
                "$comment": "for lowVolumeDefault only, the flowRate matches the uiMaxFlowRate. This does not change physical behavior and was made for UI purposes"
              },
              "defaultFlowAcceleration": {
                "$ref": "#/definitions/positiveNumber"
              },
              "defaultTipLength": {
                "$ref": "#/definitions/positiveNumber"
              },
              "defaultReturnTipHeight": {
                "$ref": "#/definitions/positiveNumber"
              },
              "fullRackReturnTipHeight": {
                "$ref": "#/definitions/positiveNumber",
                "description": "An optional number to change the height to return tips when doing a full rack."
              },
              "aspirate": {
                "type": "array",
                "items": { "$ref": "#/definitions/liquidHandlingSpecs" }
              },
              "dispense": {
                "type": "array",
                "items": { "$ref": "#/definitions/liquidHandlingSpecs" }
              },
              "uiMaxFlowRate": {
                "$ref": "#/definitions/positiveNumber",
                "$comment": "To be used in frontend applications only since it is the limit-to-lowest-max",
                "description": "An optional number to represent each pipette's supported tip max flow rate for aspirate and dispense. The limit is the lowest max flow rate given all the tip's volumes minus 2% for safety."
              }
            }
          }
        }
      }
    },
    "maxVolume": { "$ref": "#/definitions/positiveNumber" },
    "minVolume": { "$ref": "#/definitions/positiveNumber" },
    "defaultTipracks": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  }
}

=== Opentrons/opentrons/shared-data/pipette/definitions/2/liquid/eight_channel/p10/default/1_6.json
{
  "$otSharedSchema": "#/pipette/schemas/2/pipetteLiquidPropertiesSchema.json",
  "supportedTips": {
    "t10": {
      "defaultAspirateFlowRate": {
        "default": 5,
        "valuesByApiLevel": { "2.0": 5 }
      },
      "defaultDispenseFlowRate": {
        "default": 10,
        "valuesByApiLevel": { "2.0": 10 }
      },
      "defaultBlowOutFlowRate": {
        "default": 1000,
        "valuesByApiLevel": { "2.0": 1000 }
      },
      "defaultTipLength": 33.0,
      "aspirate": {
        "default": {
          "1": [
            [0.8649, 0.0374, 0.8484],
            [1.2416, -0.0987, 0.9503],
            [1.6053, -0.069, 0.9134],
            [1.9851, -0.0226, 0.839],
            [2.3481, -0.0313, 0.8561],
            [2.7207, -0.0143, 0.8164],
            [3.0702, -0.028, 0.8536],
            [4.5998, -0.0006, 0.7694],
            [6.1063, -0.0022, 0.7769],
            [7.6504, 0.0011, 0.7564],
            [9.1863, 0.0003, 0.7626],
            [10.7574, 0.0018, 0.7488],
            [12.2984, -0.4986, 6.1321]
          ]
        }
      },
      "dispense": { "default": { "1": [[12.74444519, 0.0, 0.8058688085]] } },
      "defaultPushOutVolume": 0
    }
  },
  "maxVolume": 10,
  "minVolume": 1.0,
  "defaultTipracks": [
    "opentrons/opentrons_96_tiprack_10ul/1",
    "opentrons/opentrons_96_filtertiprack_10ul/1",
    "opentrons/geb_96_tiprack_10ul/1"
  ]
}

=== Opentrons/opentrons/shared-data/pipette/definitions/2/liquid/single_channel/p1000/default/3_6.json
{
  "$otSharedSchema": "#/pipette/schemas/2/pipetteLiquidPropertiesSchema.json",
  "supportedTips": {
    "t20": {
      "uiMaxFlowRate": 57,
      "defaultAspirateFlowRate": {
        "default": 35,
        "valuesByApiLevel": { "2.14": 35 }
      },
      "defaultDispenseFlowRate": {
        "default": 57,
        "valuesByApiLevel": { "2.14": 57 }
      },
      "defaultBlowOutFlowRate": {
        "default": 57,
        "valuesByApiLevel": { "2.14": 57 }
      },
      "defaultFlowAcceleration": 24000.0,
      "defaultTipLength": 52.0,
      "defaultReturnTipHeight": 0.71,
      "aspirate": {
        "default": {
          "1": [
            [1.933333, 2.844459, 4.750159],
            [2.833333, 1.12901, 8.066694],
            [3.603333, 0.254744, 10.543779],
            [4.836667, 1.101839, 7.491414],
            [5.755, 0.277649, 11.47775],
            [6.643333, 0.14813, 12.223126],
            [7.548333, 0.145635, 12.239705],
            [8.475, 0.15097, 12.199433],
            [13.02, 0.071736, 12.870946],
            [22.318333, 0.042305, 13.254131]
          ]
        }
      },
      "dispense": {
        "default": {
          "1": [
            [1.933333, 2.844459, 4.750159],
            [2.833333, 1.12901, 8.066694],
            [3.603333, 0.254744, 10.543779],
            [4.836667, 1.101839, 7.491414],
            [5.755, 0.277649, 11.47775],
            [6.643333, 0.14813, 12.223126],
            [7.548333, 0.145635, 12.239705],
            [8.475, 0.15097, 12.199433],
            [13.02, 0.071736, 12.870946],
            [22.318333, 0.042305, 13.254131]
          ]
        }
      },
      "defaultPushOutVolume": 2
    },
    "t50": {
      "uiMaxFlowRate": 785.2,
      "defaultAspirateFlowRate": {
        "default": 478,
        "valuesByApiLevel": { "2.14": 478 }
      },
      "defaultDispenseFlowRate": {
        "default": 478,
        "valuesByApiLevel": { "2.14": 478 }
      },
      "defaultBlowOutFlowRate": {
        "default": 478,
        "valuesByApiLevel": { "2.14": 478 }
      },
      "defaultFlowAcceleration": 24000.0,
      "defaultTipLength": 57.9,
      "defaultReturnTipHeight": 0.71,
      "aspirate": {
        "default": {
          "1": [
            [0.6067, 5.4947, 0.2401],
            [0.9633, 4.2995, 0.9652],
            [1.62, 3.1217, 2.0999],
            [2.0133, 1.955, 3.9898],
            [2.47, 1.5501, 4.8051],
            [2.94, 1.0993, 5.9186],
            [3.0067, -6.841, 29.2631],
            [3.14, -0.0691, 8.9023],
            [3.4333, 1.417, 4.2356],
            [4.4633, 1.8328, 2.8082],
            [5.2867, 0.7006, 7.8614],
            [6.0733, 0.3271, 9.836],
            [8.69, 0.2834, 10.1015],
            [10.45, 0.1814, 10.9878],
            [13.7867, 0.119, 11.6399],
            [22.6567, 0.0415, 12.7084],
            [29.05, 0.03, 12.9687],
            [47.7333, 0.0207, 13.241],
            [53.74, 0.0029, 14.0865]
          ]
        }
      },
      "dispense": {
        "default": {
          "1": [
            [0.6067, 5.4947, 0.2401],
            [0.9633, 4.2995, 0.9652],
            [1.62, 3.1217, 2.0999],
            [2.0133, 1.955, 3.9898],
            [2.47, 1.5501, 4.8051],
            [2.94, 1.0993, 5.9186],
            [3.0067, -6.841, 29.2631],
            [3.14, -0.0691, 8.9023],
            [3.4333, 1.417, 4.2356],
            [4.4633, 1.8328, 2.8082],
            [5.2867, 0.7006, 7.8614],
            [6.0733, 0.3271, 9.836],
            [8.69, 0.2834, 10.1015],
            [10.45, 0.1814, 10.9878],
            [13.7867, 0.119, 11.6399],
            [22.6567, 0.0415, 12.7084],
            [29.05, 0.03, 12.9687],
            [47.7333, 0.0207, 13.241],
            [53.74, 0.0029, 14.0865]
          ]
        }
      },
      "defaultPushOutVolume": 7
    },
    "t200": {
      "uiMaxFlowRate": 802.5,
      "defaultAspirateFlowRate": {
        "default": 716,
        "valuesByApiLevel": { "2.14": 716 }
      },
      "defaultDispenseFlowRate": {
        "default": 716,
        "valuesByApiLevel": { "2.14": 716 }
      },
      "defaultBlowOutFlowRate": {
        "default": 716,
        "valuesByApiLevel": { "2.14": 716 }
      },
      "defaultFlowAcceleration": 24000.0,
      "defaultTipLength": 58.35,
      "defaultReturnTipHeight": 0.71,
      "aspirate": {
        "default": {
          "1": [
            [1.9625, 2.8528, 3.0715],
            [2.79, 1.7096, 5.3149],
            [4.5275, 0.8586, 7.6892],
            [5.5825, 0.5395, 9.1342],
            [6.745, 0.2821, 10.5708],
            [9.77, 0.1966, 11.1476],
            [11.7525, 0.1473, 11.6291],
            [19.9025, 0.0679, 12.5632],
            [33.2925, 0.0299, 13.3178],
            [51.7125, 0.0202, 13.642],
            [92.2925, 0.0078, 14.2821],
            [151.7225, 0.0028, 14.7499],
            [178.9925, 0.0018, 14.8952],
            [210.7825, 0.0007, 15.0974]
          ]
        }
      },
      "dispense": {
        "default": {
          "1": [
            [1.9625, 2.8528, 3.0715],
            [2.79, 1.7096, 5.3149],
            [4.5275, 0.8586, 7.6892],
            [5.5825, 0.5395, 9.1342],
            [6.745, 0.2821, 10.5708],
            [9.77, 0.1966, 11.1476],
            [11.7525, 0.1473, 11.6291],
            [19.9025, 0.0679, 12.5632],
            [33.2925, 0.0299, 13.3178],
            [51.7125, 0.0202, 13.642],
            [92.2925, 0.0078, 14.2821],
            [151.7225, 0.0028, 14.7499],
            [178.9925, 0.0018, 14.8952],
            [210.7825, 0.0007, 15.0974]
          ]
        }
      },
      "defaultPushOutVolume": 5
    },
    "t1000": {
      "uiMaxFlowRate": 727.3,
      "defaultAspirateFlowRate": {
        "default": 716,
        "valuesByApiLevel": { "2.14": 716 }
      },
      "defaultDispenseFlowRate": {
        "default": 716,
        "valuesByApiLevel": { "2.14": 716 }
      },
      "defaultBlowOutFlowRate": {
        "default": 716,
        "valuesByApiLevel": { "2.14": 716 }
      },
      "defaultFlowAcceleration": 24000.0,
      "defaultTipLength": 95.6,
      "defaultReturnTipHeight": 0.82,
      "aspirate": {
        "default": {
          "1": [
            [2.1, 3.2321, 1.5623],
            [3.155, 1.598, 4.994],
            [5.025, 0.512, 8.4204],
            [9.86, 0.2602, 9.6853],
            [12.29, 0.1917, 10.3606],
            [15.0, 0.058, 12.004],
            [51.305, 0.04, 12.274],
            [92.46, 0.0097, 13.8281],
            [112.25, 0.0051, 14.2545],
            [242.805, 0.0026, 14.534],
            [355.275, 0.0009, 14.965],
            [429.32, 0.0004, 15.1122],
            [626.65, 0.0003, 15.1748],
            [997.35, 0.0001, 15.3053],
            [1100.95, 0.0, 15.4221]
          ]
        }
      },
      "dispense": {
        "default": {
          "1": [
            [2.1, 3.2321, 1.5623],
            [3.155, 1.598, 4.994],
            [5.025, 0.512, 8.4204],
            [9.86, 0.2602, 9.6853],
            [12.29, 0.1917, 10.3606],
            [15.0, 0.058, 12.004],
            [51.305, 0.04, 12.274],
            [92.46, 0.0097, 13.8281],
            [112.25, 0.0051, 14.2545],
            [242.805, 0.0026, 14.534],
            [355.275, 0.0009, 14.965],
            [429.32, 0.0004, 15.1122],
            [626.65, 0.0003, 15.1748],
            [997.35, 0.0001, 15.3053],
            [1100.95, 0.0, 15.4221]
          ]
        }
      },
      "defaultPushOutVolume": 20
    }
  },
  "maxVolume": 1000,
  "minVolume": 5,
  "defaultTipracks": [
    "opentrons/opentrons_flex_96_tiprack_1000ul/1",
    "opentrons/opentrons_flex_96_tiprack_200ul/1",
    "opentrons/opentrons_flex_96_tiprack_50ul/1",
    "opentrons/opentrons_flex_96_filtertiprack_1000ul/1",
    "opentrons/opentrons_flex_96_filtertiprack_200ul/1",
    "opentrons/opentrons_flex_96_filtertiprack_50ul/1"
  ]
}
